#!/usr/bin/env node
// Schema audit — find columns the code uses that the database does not have.
//
// Nearly every silent failure in this codebase has been this one shape:
// PostgREST rejects the WHOLE request when a single column is unknown, and
// most call sites never read `error`, so the feature quietly shows nothing.
// Finding these by touching a nearby feature is not a strategy.
//
//   node scripts/schema-audit.mjs          -> writes schema-audit.sql
//
// Paste the generated SQL into the Supabase SQL Editor. It returns one row per
// (table, column) the code references that the database does not have.
//
// This reads the code only; the database is the other half and it decides.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs'
import { join, extname } from 'path'

const ROOT = 'src'
const EXT = new Set(['.js', '.jsx', '.ts', '.tsx'])

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p, out)
    else if (EXT.has(extname(p))) out.push(p)
  }
  return out
}

// A chain is everything between .from('x') and the next .from( — good enough,
// and erring toward over-collecting is right: a false positive costs one
// glance, a false negative is the bug we are hunting.
const FROM = /\.from\(\s*['"`]([a-z0-9_]+)['"`]\s*\)/gi

// Column-bearing calls. `select` gets its own parser because of embeds.
const FILTERS = /\.(eq|neq|gt|gte|lt|lte|like|ilike|is|in|contains|order|not)\(\s*['"`]([a-z0-9_]+)['"`]/gi
const SELECTS = /\.select\(\s*['"`]([^'"`]*)['"`]/gi
const WRITE = /\.(insert|update|upsert)\(\s*\{/gis

// Keys of the TOP-LEVEL object only. `meta: { manager_name, note }` stores one
// jsonb column named meta; harvesting its inner keys reported two columns that
// were never columns, and noise like that is how a real finding gets waved off.
function topLevelKeys(src, openBrace) {
  let depth = 0, i = openBrace, out = [], buf = ''
  for (; i < src.length && i < openBrace + 4000; i++) {
    const ch = src[i]
    if (ch === '{' || ch === '[' || ch === '(') { depth++; if (depth > 1) continue }
    else if (ch === '}' || ch === ']' || ch === ')') { depth--; if (depth === 0) break; continue }
    if (depth === 1) buf += ch
  }
  for (const m of buf.matchAll(/(?:^|,)\s*([a-z0-9_]+)\s*(?::|,|$)/gi)) out.push(m[1])
  return out
}

const found = new Map()   // table -> Set(columns)
const add = (t, c) => {
  if (!c || c === '*' || c.includes('(') || c.includes(':')) return
  // `organizations.${poolKey}` is a column chosen at runtime, not a literal.
  if (!/^[a-z][a-z0-9_]*$/i.test(c)) return
  if (!found.has(t)) found.set(t, new Set())
  found.get(t).add(c)
}

for (const file of walk(ROOT)) {
  const src = readFileSync(file, 'utf8')
  const marks = [...src.matchAll(FROM)]
  marks.forEach((m, i) => {
    const table = m[1]
    const chain = src.slice(m.index, Math.min(marks[i + 1]?.index ?? src.length, m.index + 400))
    for (const f of chain.matchAll(FILTERS)) add(table, f[2])
    for (const s of chain.matchAll(SELECTS)) {
      // strip embedded resources: "a, rel(b,c)" -> a
      s[1].replace(/\w+\s*\([^)]*\)/g, '').split(',').forEach(c => add(table, c.trim()))
    }
    for (const w of chain.matchAll(WRITE)) {
      for (const k of topLevelKeys(chain, w.index + w[0].length - 1)) add(table, k)
    }
  })
}

const pairs = []
for (const [t, cols] of [...found].sort()) for (const c of [...cols].sort()) pairs.push([t, c])

const values = pairs.map(([t, c]) => `('${t}','${c}')`).join(',\n  ')
const sql = `-- Generated by scripts/schema-audit.mjs — do not edit by hand.
-- ${pairs.length} (table, column) pairs referenced by the code.
--
-- Returns one row per column the CODE uses that the DATABASE does not have.
-- An empty result is the goal. Anything returned is a request PostgREST is
-- rejecting outright, which in this codebase means a feature silently showing
-- nothing rather than raising an error.
--
-- Tables listed as missing entirely are usually fine (a table that only exists
-- in the other project); a MISSING COLUMN on a table that DOES exist is the
-- real finding.

WITH used(tbl, col) AS (VALUES
  ${values}
)
SELECT u.tbl AS table_name,
       u.col AS missing_column,
       CASE WHEN t.table_name IS NULL THEN 'table does not exist here'
            ELSE 'COLUMN MISSING — requests using it fail' END AS verdict
FROM used u
LEFT JOIN information_schema.tables t
  ON t.table_schema = 'public' AND t.table_name = u.tbl
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public' AND c.table_name = u.tbl AND c.column_name = u.col
WHERE c.column_name IS NULL
ORDER BY (t.table_name IS NULL), u.tbl, u.col;
`
writeFileSync('schema-audit.sql', sql)
console.log(`  ${pairs.length} column references across ${found.size} tables -> schema-audit.sql`)
